version: '3.4'
services:
  employee:
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=test
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    image: employee
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:443'
    volumes:
      - ~/.aspnet/https:/https:ro
    links:
       - db
  db:
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: SqlServer2019
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'